AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploys a role used by CodePipeline to deploy CloudFormation stacks

Parameters:

  TargetAccountForCFnDeployment:
    Type: String
    Description: AWS Account Id of the identity/federation account.
    MaxLength: 12
    MinLength: 12

Resources:
  DeploymentRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: DeploymentRole
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - cloudformation.amazonaws.com
                  - codepipeline.amazonaws.com
                AWS:
                  - !Sub arn:aws:iam::${TargetAccountForCFnDeployment}:root
              Action:
                - sts:AssumeRole
        Path: /
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AdministratorAccess